### ISSUE TITLE
Build fails on Linux: undefined reference to `__atomic_load_16'

### ISSUE THREAD

**Issue by codecnotsupported** [cmaughan/vklive#2]
```
[100%] Linking CXX executable Rezonality
/usr/bin/ld: libvklive.a(vulkan_scene.cpp.o): in function `vulkan::vulkan_scene_render(vulkan::VulkanContext&, vulkan::RenderContext&, Scene&)':
vulkan_scene.cpp:(.text+0xb6ee): undefined reference to `__atomic_load_16'
/usr/bin/ld: libvklive.a(audio_analysis.cpp.o): in function `Audio::audio_analysis_calculate_spectrum_bands(Audio::AudioAnalysis&, Audio::AudioAnalysisData&)':
audio_analysis.cpp:(.text+0x4ed): undefined reference to `__atomic_load_16'
/usr/bin/ld: audio_analysis.cpp:(.text+0x51d): undefined reference to `__atomic_store_16'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/Rezonality.dir/build.make:264: Rezonality] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:129: CMakeFiles/Rezonality.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by cmaughan** [comment]
Needs `#include <atomic>` at top of the failing file. Fair warning: very little testing on Linux so far!

**Comment by cmaughan** [comment]
Actually a thread library included

**Comment by cmaughan** [comment]
-lpthread in the CMakeLists is probably what's needed; sorry, I can't fix it currently.

**Comment by codecnotsupported** [comment]
-latomic was missing.

```
CMakeLists.txt:274
-     target_link_libraries(Rezonality PRIVATE X11 Xext xcb)
+    target_link_libraries(Rezonality PRIVATE X11 Xext xcb atomic)
```

**Comment by cmaughan** [comment]
Thanks, I've made this fix, and all builds now complete.  @codecnotsupported did you get it to run on Linux?

**Comment by codecnotsupported** [comment]
> Thanks, I've made this fix, and all builds now complete. @codecnotsupported did you get it to run on Linux?

It runs...-ish, my GPU doesn't support ray-tracing so it complains about missing extensions, and exits.

**Comment by cmaughan** [comment]
> > Thanks, I've made this fix, and all builds now complete. @codecnotsupported did you get it to run on Linux?
> 
> It runs...-ish, my GPU doesn't support ray-tracing so it complains about missing extensions, and exits.

Hmm, you don't need ray tracing for any of the current examples.  Let me look...

**Comment by cmaughan** [comment]
I can

> > > Thanks, I've made this fix, and all builds now complete. @codecnotsupported did you get it to run on Linux?
> > 
> > 
> > It runs...-ish, my GPU doesn't support ray-tracing so it complains about missing extensions, and exits.
> 
> Hmm, you don't need ray tracing for any of the current examples. Let me look...

I can't see anywhere I ask for ray tracing extensions; I will try to setup a linux system to test it.

**Comment by codecnotsupported** [comment]
To clarify I _presumed_ you queried Vulkan for ray tracing extensions as requirement because it's the only extension I can think of that my card doesn't support (well that and mesh shaders, but those aren't not vendor neutral yet), the logs don't mention which extensions I'm missing. So it might be something else.
```
Instance Extensions:
VK_EXT_acquire_drm_display:
        Version: 1

VK_EXT_acquire_xlib_display:
        Version: 1

VK_EXT_debug_report:
        Version: 10

VK_EXT_debug_utils:
        Version: 2

VK_EXT_direct_mode_display:
        Version: 1

VK_EXT_display_surface_counter:
        Version: 1

VK_KHR_device_group_creation:
        Version: 1

VK_KHR_display:
        Version: 23

VK_KHR_external_fence_capabilities:
        Version: 1

VK_KHR_external_memory_capabilities:
        Version: 1

VK_KHR_external_semaphore_capabilities:
        Version: 1

VK_KHR_get_display_properties2:
        Version: 1

VK_KHR_get_physical_device_properties2:
        Version: 2

VK_KHR_get_surface_capabilities2:
        Version: 1

VK_KHR_portability_enumeration:
        Version: 1

VK_KHR_surface:
        Version: 25

VK_KHR_surface_protected_capabilities:
        Version: 1

VK_KHR_wayland_surface:
        Version: 6

VK_KHR_xcb_surface:
        Version: 6

VK_KHR_xlib_surface:
        Version: 6

VK_LAYER_VALVE_steam_fossilize_32
VK_LAYER_VALVE_steam_overlay_32
VK_LAYER_VALVE_steam_overlay_64
VK_LAYER_VALVE_steam_fossilize_64
VK_LAYER_MESA_device_select
VK_LAYER_NV_optimus
VK_LAYER_KHRONOS_profiles
VK_LAYER_KHRONOS_validation
VK_LAYER_LUNARG_monitor
VK_LAYER_KHRONOS_synchronization2
VK_LAYER_LUNARG_screenshot
VK_LAYER_LUNARG_gfxreconstruct
VK_LAYER_LUNARG_api_dump
VK_LAYER_MESA_overlay
terminate called after throwing an instance of 'vk::ExtensionNotPresentError'
  what():  vk::PhysicalDevice::createDevice: ErrorExtensionNotPresent
Aborted (core dumped)
```

**Comment by codecnotsupported** [comment]
The error goes away with (and gives a new error 2nd post below):
vklive/src/vulkan/vulkan_utils.cpp:296
```
-    return { VK_KHR_SWAPCHAIN_EXTENSION_NAME, "VK_KHR_portability_subset" };
+   return { VK_KHR_SWAPCHAIN_EXTENSION_NAME};
```
Seems like I don't have the  "VK_KHR_portability_subset" EXT?

**Comment by codecnotsupported** [comment]
Also the debug build (when you run ./build.sh), builds but crashes with
```
Rezonality: /home/user/Downloads/vklive/src/file/file.cpp:372: std::filesystem::__cxx11::path file_appdata_path(): Assertion `!"Fixme"' failed.
Aborted (core dumped)
```

**Comment by codecnotsupported** [comment]
The Release build still fails at runtime with:
```
...
VK_LAYER_KHRONOS_synchronization2
VK_LAYER_LUNARG_screenshot
VK_LAYER_LUNARG_gfxreconstruct
VK_LAYER_LUNARG_api_dump
VK_LAYER_MESA_overlay
/home/user/Downloads/vklive/run_tree/bin/mac/glslangValidator: 1: Syntax error: "(" unexpected
terminate called after throwing an instance of 'vk::OutOfHostMemoryError'
  what():  vk::Device::createShaderModule: ErrorOutOfHostMemory
Aborted (core dumped)
```
I run Linux, not mac. So I beg the question. Why does it run the mac version of `glslangValidator`?
Even better why is the Linux version of glslangValidator a mac binary???
```
User@Hostname:~/Downloads/vklive/run_tree/bin/linux$ file glslangValidator 
glslangValidator: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE>] [arm64]
```

**Comment by cmaughan** [comment]
Yes, welcome to untested Linux :) 
So fixing the right glslangValidator should sort out linux; I suspect it just needs the right one from the linux Vulkan SDK copying into place.
I think the portability subset should probably be Mac only (it lets it run with Molten VK, IIRC).  I'll make that change.

**Comment by codecnotsupported** [comment]
![image](https://user-images.githubusercontent.com/2294209/179244510-aca9b1b6-77ed-4d83-9470-53fd53645efb.png)
I copied my glslangValidator to the mac folder, and it runs.
Is the default project suppose to not render anything or am I not suppose to run from the build directory?

**Comment by cmaughan** [comment]
It looks like your screen.frag shader has failed to compile; if you click it and move the cursor to the red highlight in the shader, you should see a reason why

**Comment by codecnotsupported** [comment]
![image](https://user-images.githubusercontent.com/2294209/179310037-7309c50f-cd64-4142-8009-a468d057cf60.png)
Seems like the ./run_tree/textures/noise.png isn't found.

**Comment by cmaughan** [comment]
OK, that's progress.  This probably goes back to your debug message:
`Rezonality: /home/user/Downloads/vklive/src/file/file.cpp:372: std::filesystem::__cxx11::path file_appdata_path(): Assertion `!"Fixme"' failed.
`
Looks like I need to add a missing function.  I've got my raspberry pi out, will try to get things building/running on it this weekend.

**Comment by cmaughan** [comment]
I managed to get a linux setup going and debugged the behaviour.  I can now load the 2 example projects.
I'm sure there will be more things to fix on Linux, but it at least runs now.  Stabilising the other OS is lower on the priority list than getting a version 1 I'm happy with - that involves some reworking of the renderer and some quality of life fixes to the editor.  Then I will try to make sure all platforms are fully functional.
